name: Manage the "latest-stable" branch

# Controls when the workflow will run
on:
  push:

permissions: write-all

jobs:
  manage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get the latest version
        id: get-ref
        run: echo "ref=$(git tag | awk '{print $0}END{print "zzzz"}' | grep -E 'v.*' | sort -Vr | head -n1)" | tee "$GITHUB_OUTPUT"
        
      - name: Move the "latest-stable" branch
        run: git branch --force latest-stable ${{ steps.get-ref.outputs.ref }}
        
      - name: Push the "latest-stable" branch
        run: git push --force origin latest-stable
